# Nome da Action:
name: Snake Game

# Controlador do tempo que será feito a atualização dos arquivos.
on:
  schedule:
    # Será atualizado a cada 5 horas.
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checkout do repositório utilizando a versão mais recente da action
      - uses: actions/checkout@v3

      # Geração dos arquivos da cobrinha
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Vagnerflj # Substitua pelo seu nome de usuário do GitHub
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Verificação do status do git
      - run: git status

      # Configuração do usuário do Git
      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # Commit das alterações e push para o branch master
      - name: Commit and Push changes
        run: |
          git add .
          git commit -m "Update snake game"
          git push origin main 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Publicação dos arquivos gerados na branch 'output'
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
